server:
  port: 8100
spring:
  application:
    name: producer-server
  # zipkin 链路跟踪
  zipkin:
    base-url: http://localhost:9411/
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8000/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoint:
    web:
      exposure:
        include: hystrix.stream