server:
  port: 8200
spring:
  application:
    name: customer-server
  # zipkin为分布式链路调用监控系统，聚合各业务系统调用延迟数据，达到链路调用监控跟踪。
  zipkin:
    base-url: http://localhost:9411/
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8000/eureka/
# 配置feign启用hystrix
feign:
  hystrix:
    enabled: true
#  实现对Hystrix Dashboard 单实例节点的监控，集群需要整合Turbine
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
swagger:
  base-package: com.ruicheng.controller