server:
  port: 8200
spring:
  application:
    name: customer-server
  # zipkin为分布式链路调用监控系统，聚合各业务系统调用延迟数据，达到链路调用监控跟踪。
  zipkin:
    base-url: http://localhost:9411/
  #使用消息中间件收集hystrix监控数据
  rabbitmq:
    host: 119.29.222.73
    port: 5672
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@peer1:8000/eureka/,http://admin:123456@peer2:8001/eureka/
  instance:
    prefer-ip-address: true
# 配置feign启用hystrix
feign:
  hystrix:
    enabled: true
#  实现对Hystrix监控
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
swagger:
  base-package: com.ruicheng.controller