server:
  port: 8200
spring:
  application:
    name: customer-server
  zipkin:
    base-url: http://localhost:9411/
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8000/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoint:
    web:
      exposure:
        include: hystrix.stream
swagger:
  base-package: com.ruicheng.controller