server:
  port: 8300
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ruichenggit/config.git #配置git仓库的地址
          username: ruichenggit
          password: rRCRQ2018?12313
          #配置git仓库下的相对地址，可以配置多个，用 , 分割
          search-paths: config-repo
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@peer1:8000/eureka/,http://admin:123456@peer2:8001/eureka/
  instance:
    prefer-ip-address: true
#Spring Cloud Config也提供本地存储配置的方式。
#我们只需要设置属性spring.profiles.active=native，Config Server会默认从应用的src/main/resource目录下检索配置文件。
#也可以通过spring.cloud.config.server.native.searchLocations=file:E:/properties/属性来指定配置文件的位置。
#虽然Spring Cloud Config提供了这样的功能，但是为了支持更好的管理内容和版本控制的功能，还是推荐使用git的方式。